### ISSUE TITLE
input files

### ISSUE THREAD

**Issue by emunte** [eol017/CNV-Z#1]
Hi!

First of all, thank you for your work.
I am eager to explore and utilize your tool; however, I have encountered an error. It is possible that I am not correctly inputting the parameters. My understanding is that I should specify the BAM files (please correct me if I am mistaken).
Eg: 

`julia -t 8 CNV-Z.jl dataset/s17296.bam dataset/s17297.bam `

But I get : 
```

ERROR: LoadError: TaskFailedException
Stacktrace:
 [1] wait
   @ ./task.jl:345 [inlined]
 [2] threading_run(fun::var"#2#threadsfor_fun#3"{var"#2#threadsfor_fun#1#4"{Vector{String}}}, static::Bool)
   @ Base.Threads ./threadingconstructs.jl:38
 [3] top-level scope
   @ ./threadingconstructs.jl:89

    nested task error: SystemError: opening file "mdepth-dataset/s17296.bam.txt": No such file or directory
    Stacktrace:
      [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
        @ Base ./error.jl:176
      [2] #systemerror#80
        @ ./error.jl:175 [inlined]
      [3] systemerror
        @ ./error.jl:175 [inlined]
      [4] open(fname::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Bool, append::Nothing)
        @ Base ./iostream.jl:293
      [5] open(fname::String, mode::String; lock::Bool)
        @ Base ./iostream.jl:356
      [6] open(fname::String, mode::String)
        @ Base ./iostream.jl:355
      [7] open(::var"#2#5"{String}, ::String, ::Vararg{String}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
        @ Base ./io.jl:382
      [8] open
        @ ./io.jl:381 [inlined]
      [9] macro expansion
        @ ~/SOFTX-D-23-00424/CNV-Z.jl:9 [inlined]
     [10] (::var"#2#threadsfor_fun#3"{var"#2#threadsfor_fun#1#4"{Vector{String}}})(tid::Int64; onethread::Bool)
        @ Main ./threadingconstructs.jl:84
     [11] #2#threadsfor_fun
        @ ./threadingconstructs.jl:51 [inlined]
     [12] (::Base.Threads.var"#1#2"{var"#2#threadsfor_fun#3"{var"#2#threadsfor_fun#1#4"{Vector{String}}}, Int64})()
        @ Base.Threads ./threadingconstructs.jl:30

```

Can you please help me? It's the first time I use a program written in julia.

Thanks in advance.

Eli

**Comment by eol017** [comment]
Hi an thank you for you email! I will have a look at your error code and see if I can point you to a solution.
Kind regards,

Emma Adolfsson

Från: Elisabet Munté ***@***.***>
Skickat: den 9 november 2023 11:46
Till: eol017/CNV-Z ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: [eol017/CNV-Z] input files (Issue #1)

Observera: Det här e-postmeddelandet kommer från en avsändare utanför organisationen. Klicka inte på länkar och öppna inte bilagor om du inte känner igen avsändaren och vet att innehållet är säkert.



Hi!

First of all, thank you for your work.
I am eager to explore and utilize your tool; however, I have encountered an error. It is possible that I am not correctly inputting the parameters. My understanding is that I should specify the BAM files (please correct me if I am mistaken).
Eg:

julia -t 8 CNV-Z.jl dataset/s17296.bam dataset/s17297.bam

But I get :



ERROR: LoadError: TaskFailedException

Stacktrace:

 [1] wait

   @ ./task.jl:345 [inlined]

 [2] threading_run(fun::var"#2#threadsfor_fun#3"{var"#2#threadsfor_fun#1#4"{Vector{String}}}, static::Bool)

   @ Base.Threads ./threadingconstructs.jl:38

 [3] top-level scope

   @ ./threadingconstructs.jl:89



    nested task error: SystemError: opening file "mdepth-dataset/s17296.bam.txt": No such file or directory

    Stacktrace:

      [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)

        @ Base ./error.jl:176

      [2] #systemerror#80

        @ ./error.jl:175 [inlined]

      [3] systemerror

        @ ./error.jl:175 [inlined]

      [4] open(fname::String; lock::Bool, read::Nothing, write::Nothing, create::Nothing, truncate::Bool, append::Nothing)

        @ Base ./iostream.jl:293

      [5] open(fname::String, mode::String; lock::Bool)

        @ Base ./iostream.jl:356

      [6] open(fname::String, mode::String)

        @ Base ./iostream.jl:355

      [7] open(::var"#2#5"{String}, ::String, ::Vararg{String}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})

        @ Base ./io.jl:382

      [8] open

        @ ./io.jl:381 [inlined]

      [9] macro expansion

        @ ~/SOFTX-D-23-00424/CNV-Z.jl:9 [inlined]

     [10] (::var"#2#threadsfor_fun#3"{var"#2#threadsfor_fun#1#4"{Vector{String}}})(tid::Int64; onethread::Bool)

        @ Main ./threadingconstructs.jl:84

     [11] #2#threadsfor_fun

        @ ./threadingconstructs.jl:51 [inlined]

     [12] (::Base.Threads.var"#1#2"{var"#2#threadsfor_fun#3"{var"#2#threadsfor_fun#1#4"{Vector{String}}}, Int64})()

        @ Base.Threads ./threadingconstructs.jl:30



Can you please help me? It's the first time I use a program written in julia.

Thanks in advance.

Eli

**Comment by eol017** [comment]
Hi! 
The problem is your naming of the bam infiles.
 julia -t 8 CNV-Z.jl dataset/s17296.bam dataset/s17297.bam
The program thinks that sample identities are: dataset/s17296.bam dataset/s17297.bam etc
The remedy would be to
1) ensure that your bam files are coordinate sorted (which is probably true already)
2) rename them with the suffix “sorted.bam” instead of “.bam”
3) change directory of your terminal window to your “dataset” directory
4) the identities of your files will now be s17296 s17297 etc
5) type julia -t 8 CNV-Z.jl s17296 s17297 …
 
An alternative solution if you don’t want to rename your files and run the script in the dataset directory would be to remove “.sorted” (marked in red below)
in the CNV-Z script:
 
[Threads.@threads](mailto:Threads.@threads) for i in ARGS
open("mdepth-$i.txt","w") do io
write(io,read(`samtools depth -a -b hglft_ICR96target.bed $i.sorted.bam`))
end
end
 
You can then run the command: julia -t 8 CNV-Z.jl dataset/s17296 dataset/s17297 …

**Comment by emunte** [comment]
Hi!
Thank you for your response.
I have changed the name of my bam files to .sorted.bam (they were sorted)  and I have changed the directory.
Now the program starts computing but I get this error:


```
julia-1.8.1/bin/julia -t 8 CNV-Z.jl s17296 s17297

["s17296", "s17297"]
ERROR: LoadError: MethodError: no method matching /(::SentinelArrays.MissingVector, ::Missing)
Closest candidates are:
  /(::AbstractVector, ::LinearAlgebra.UniformScaling) at ~/julia-1.8.1/share/julia/stdlib/v1.8/LinearAlgebra/src/uniformscaling.jl:270
  /(::AbstractArray, ::Number) at arraymath.jl:24
  /(::AbstractVector, ::Union{LinearAlgebra.UnitLowerTriangular, LinearAlgebra.UnitUpperTriangular}) at ~/julia-1.8.1/share/julia/stdlib/v1.8/LinearAlgebra/src/triangular.jl:1655
  ...
Stacktrace:
 [1] top-level scope
   @ ~/SOFTX-D-23-00424/CNV-Z.jl:37
in expression starting at /home/croca/SOFTX-D-23-00424/CNV-Z.jl:36
```




Do I need to install some module or something? 
Thanks in advance,

Eli

**Comment by eol017** [comment]
Hi Elisabet,
I suggest running the program with at least 8 samples. Make sure the Statistics module is installed. Try the command:  “using Statistics” in the REPL mode to find out.
If no success, could you please send a few lines of the intermediary “mdepth-s17296.h.txt” file, from which we could start troubleshooting
Best regards,
Emma and Jon

**Comment by emunte** [comment]
Hi,

Thanks for your assistance.
I believe I've identified the issue:
Your bed file uses a 'chr' prefix for chromosomes, which differs from my bam file's naming convention. This mismatch caused the generation of an empty 'mdepth-s17296.h.txt' file and triggered the error message.

Adjusting the bed file naming convention resolved the issue, and the program now works smoothly!

Just to confirm, after running the FilterICR96.jl script for 'Fx-SAMPLE.res.2.3.csv', are negative z-scores indicative of deletions and positive ones indicative of duplications?

Moreover, I'd like to offer some user feedback: it would be great in future versions if there's an option to designate output file locations separate from input files. Additionally, having a FilterScript where users can input sample names as parameters without needing to modify the code would enhance usability.

Thank you once again for your time and effort! :)

Best regards,
Eli
