### ISSUE TITLE
ERROR: ParseError:

### ISSUE THREAD

**Issue by removedraft** [eol017/CNV-Z#3]
Hello. When I tried to run the tool, an error occurred.

```
julia> -t 8 ./CNV-Z-main/CNV-Z.jl /mnt/c/Users/if061/Downloads/NG1NT0BBN0.mm2.sortdup.bqsr.bam
ERROR: ParseError:
# Error @ REPL[4]:1:3
-t 8 ./CNV-Z-main/CNV-Z.jl /mnt/c/Users/if061/Downloads/NG1NT0BBN0.mm2.sortdup.bqsr.bam
# └───────────────────────────────────────────────────────────────────────────────────┘ ── extra tokens after end of expression
Stacktrace:
 [1] top-level scope
   @ none:1
```
![스크린샷(860)](https://github.com/eol017/CNV-Z/assets/72497449/fed36c37-ff8b-438e-816a-64c05495315f)

Can anybody help me on this issue? I ran it on WSL Ubuntu.

**Comment by eol017** [comment]
Hi Removedraft,

You got the ERROR:

julia> -t 8 ./CNV-Z-main/CNV-Z.jl /mnt/c/Users/if061/Downloads/NG1NT0BBN0.mm2.sortdup.bqsr.bam
ERROR: ParseError:
# Error @ REPL[4]:1:3
-t 8 ./CNV-Z-main/CNV-Z.jl /mnt/c/Users/if061/Downloads/NG1NT0BBN0.mm2.sortdup.bqsr.bam
# └───────────────────────────────────────────────────────────────────────────────────┘ ── extra tokens after end of expression
Stacktrace:
 [1] top-level scope
   @ none:1

It looks as if you are trying to run CNV-Z.jl in the REPL interactive mode. Don’t do that.
Instead, copy at least 8 bamfiles to your directory ‘CNV-Z-main’ and rename them according to the naming pattern “<sampleID>.sorted.bam”, which in your case presumably would be something like “NG1NT0BBN0.sorted.bam”. I suggest that you also copy the header.txt file and the target.bed file to this directory. 
Then, open the CNV-Z.jl program in a text editor e.g. VIM and replace “hglft_ICR96target.bed” (marked in red below) with the name (path) of your target bed file. If your sorted bam files are named with another pattern than “<sampleID>.sorted .bam” the yellow highlighted text on line 10 should also be altered according to your naming convention. 
_____________________________________________________________

#Usage: julia -t 8 CNV-Z.jl <sampleID> [<sampleID> <sampleID> ... ]
#Adjust the number of threads, and paths to targets and bamfiles below if necessary

using CSV, DataFrames, Statistics, Base.Threads

println(ARGS)

Threads.@threads for i in ARGS
	open("mdepth-$i.txt","w") do io
		write(io,read(`samtools depth -a -b hglft_ICR96target.bed $i.sorted.bam`))
	end
end

for i in ARGS
	open("mdepth-$i.h.txt","w") do io
		write(io,read(`cat header.txt mdepth-$i.txt`))
	end
end
…

Finally, open a terminal window in the same directory and (I am guessing your sampleIDs) type the command:

julia -t 8 CNV-Z.jl NG1NT0BBN0 NG1NT0BBN1 NG1NT0BBN2 NG1NT0BBN3 NG1NT0BBN4 NG1NT0BBN5 NG1NT0BBN6 NG1NT0BBN7 

If this doesn´t work it would help if you send us a copy of the output and a few lines of a mdepth-<sampleID>.h.txt that hopefully has been created in the same directory.

Best wishes,
Emma
